// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kokos.Api.Models;

#nullable disable

namespace kokos.Api.Migrations.UserEventDb
{
    [DbContext(typeof(UserEventDbContext))]
    [Migration("20251129144711_Eventy")]
    partial class Eventy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventInfoUserSimple", b =>
                {
                    b.Property<long>("EventInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("UczestnicyPotwierdzeniId")
                        .HasColumnType("integer");

                    b.HasKey("EventInfoId", "UczestnicyPotwierdzeniId");

                    b.HasIndex("UczestnicyPotwierdzeniId");

                    b.ToTable("EventParticipantsConfirmed", (string)null);
                });

            modelBuilder.Entity("EventInfoUserSimple1", b =>
                {
                    b.Property<long>("EventInfo1Id")
                        .HasColumnType("bigint");

                    b.Property<int>("UczestnicyChetniId")
                        .HasColumnType("integer");

                    b.HasKey("EventInfo1Id", "UczestnicyChetniId");

                    b.HasIndex("UczestnicyChetniId");

                    b.ToTable("EventParticipantsWilling", (string)null);
                });

            modelBuilder.Entity("kokos.Api.Models.EventInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Godzina")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("integer");

                    b.Property<double>("Szerokosc")
                        .HasColumnType("double precision");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Wysokosc")
                        .HasColumnType("double precision");

                    b.Property<bool>("Zakonczone")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("Wydarzenia");
                });

            modelBuilder.Entity("kokos.Api.Models.UserSimple", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("EventInfoUserSimple", b =>
                {
                    b.HasOne("kokos.Api.Models.EventInfo", null)
                        .WithMany()
                        .HasForeignKey("EventInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kokos.Api.Models.UserSimple", null)
                        .WithMany()
                        .HasForeignKey("UczestnicyPotwierdzeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventInfoUserSimple1", b =>
                {
                    b.HasOne("kokos.Api.Models.EventInfo", null)
                        .WithMany()
                        .HasForeignKey("EventInfo1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kokos.Api.Models.UserSimple", null)
                        .WithMany()
                        .HasForeignKey("UczestnicyChetniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("kokos.Api.Models.EventInfo", b =>
                {
                    b.HasOne("kokos.Api.Models.UserSimple", "Organizator")
                        .WithMany("Wydarzenia")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("kokos.Api.Models.UserSimple", b =>
                {
                    b.Navigation("Wydarzenia");
                });
#pragma warning restore 612, 618
        }
    }
}
